apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: product-catalog-app
  labels:
    commit: 48f74f435786d54673ac8c01f06a5fc69fb4b484
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog-app
  template:
    metadata:
      labels:
        app: product-catalog-app
        commit: 48f74f435786d54673ac8c01f06a5fc69fb4b484
    spec:
      containers:
      - name: product-catalog-app-container
        image: derekoneil/alpha-office-product-catalog
        imagePullPolicy: Always
        ports:
        - name: pc-app-port
          containerPort: 80
          protocol: TCP
      imagePullSecrets:
        - name: wercker
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  annotations: 
    service.beta.kubernetes.io/oci-load-balancer-shape: 400Mbps
  labels:
    app: product-catalog-app
    commit: 48f74f435786d54673ac8c01f06a5fc69fb4b484
spec:
  ports:
  - port: 30000
    targetPort: 80
  selector:
    app: product-catalog-app
    commit: 48f74f435786d54673ac8c01f06a5fc69fb4b484
  type: LoadBalancer
---
